FROM ubuntu:$INJECT_UBUNTU_DOCKER_TAG

# Install base requirements
ENV TZ=Europe/Paris
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
echo $TZ > /etc/timezone

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install --no-install-recommends -y wget \
    unzip \
    git \
    ssh \
    ca-certificates && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

CMD ["bash"]

